title: Week in Filecoin
email: noreply@jamiedubs.com
description: >- # this means to ignore newlines until "baseurl:"
  Running notes on IPFS and Filecoin development.
baseurl: "/week-in-filecoin" # the subpath of your site, e.g. /blog
url: "https://www.jamiedubs.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jamiew
github_username:  jamiew

# Build settings
markdown: kramdown
# theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
